name: Make Release Chart

on:
    workflow_call:
        inputs:
            APP_NAME:
                type: string
                required: true
            APP_VERSION:
                type: string
                required: true
            CHART_FOLDER:
                type: string
                required: true
            DOCKER_REGISTRY:
                description: "Docker registry for helm chart"
                type: string
                required: false
                default: "docker-registry.trendagent.ru:5000"
        secrets:
            DOCKER_REGISTRY_USER:
                required: true
            DOCKER_REGISTRY_PASSWORD:
                required: true

jobs:
    chart:
        runs-on: [self-hosted, docker-runner]
        steps:
#            -   name: Configure git to trust the workspace despite the different owner
#                run:
#                    git config --global --add safe.directory "$GITHUB_WORKSPACE"

            -   name: Checkout
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Install Helm
                uses: azure/setup-helm@v3
                with:
                    version: v3.9.4

            -   name: Log into Docker registry
                uses: docker/login-action@v2
                with:
                    registry: ${{ inputs.DOCKER_REGISTRY }}
                    username: ${{ secrets.DOCKER_REGISTRY_USER }}
                    password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

            -   name: Update Chart
                uses: danielr1996/envsubst-action@1.0.0
                env:
                    APP_NAME: ${{ inputs.APP_NAME }}
                    APP_VERSION: ${{ inputs.APP_VERSION }}
                with:
                    input: ${{ inputs.CHART_FOLDER }}/Chart.yaml
                    output: ${{ inputs.CHART_FOLDER }}/Chart.yaml
                    

            -   name: Publish chart
                shell: bash
                run: |
                    cat ${{ inputs.CHART_FOLDER }}/Chart.yaml
                    cd ${{ inputs.CHART_FOLDER }}
                    helm registry login -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${{ inputs.DOCKER_REGISTRY }}
                    helm package ./
#                    helm push ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tgz oci://${{ inputs.DOCKER_REGISTRY }}/helm-charts

