name: Make Release Chart

on:
  workflow_call:
    inputs:
      APP_NAME:
        type: string
        required: true
      APP_VERSION:
        type: string
        required: true
      CHART_FOLDER:
        type: string
        required: true
    secrets:
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
      DOCKER_REGISTRY:
        required: false

jobs:
  chart:
    runs-on: [ self-hosted, docker-runner ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.4

      - name: Log into Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Update Chart
        #                uses: mshick/fast-envsubst@v1
        uses: Dgeliko/envsubst@v1.1
        env:
          APP_NAME: ${{ inputs.APP_NAME }}
          APP_VERSION: ${{ inputs.APP_VERSION }}
        with:
          in-file: ${{ inputs.CHART_FOLDER }}/Chart.yaml
          out-file: ${{ inputs.CHART_FOLDER }}/Chart.yaml

      - name: Publish chart
        shell: bash
        run: |
          cd ${{ inputs.CHART_FOLDER }}
          helm registry login -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}
          helm package ./
          helm push ${{ inputs.APP_NAME }}-${{ inputs.APP_VERSION }}.tgz oci://${{ secrets.DOCKER_REGISTRY }}/helm-charts
