name: TR PRO deploy

on:
  workflow_call:
    inputs:
      APP_NAME:
        type: string
        required: false
        default: ''
      APP_VERSION:
        type: string
        required: false
        default: ''
      LOCATION:
        type: string
        required: true
      DOCKER_REGISTRY:
        description: "Docker registry for helm chart"
        type: string
        required: false
        default: "docker-registry.trendagent.ru:5000"
    secrets:
      TOKEN:
        required: true
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
      TA_PROD_KUBE_CONFIG:
        required: false

jobs:
  release:
    runs-on: [ self-hosted, docker-runner ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: trend-dev/${{ inputs.APP_NAME }}
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - name: Check
        run: |
          echo ${{ inputs.APP_NAME }}
          echo ${{ inputs.APP_VERSION }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.4

      - name: Add TA-PRO Kube config
        shell: bash
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.TA_PROD_KUBE_CONFIG }} | base64 -d > ~/.kube/config

      - name: Update Chart
        #                uses: mshick/fast-envsubst@v1
        uses: Dgeliko/envsubst@v1.1
        env:
          APP_NAME: ${{ inputs.APP_NAME }}
          APP_VERSION: ${{ inputs.APP_VERSION }}
        with:
          in-file: tools/charts/${{ inputs.APP_NAME }}/Chart.yaml
          out-file: tools/charts/${{ inputs.APP_NAME }}/Chart.yaml

      - name: Upgrade prod
        shell: bash
        run: |
          helm registry login -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} ${{ inputs.DOCKER_REGISTRY }}
          cd ./tools/charts/
          helm upgrade ${{ inputs.APP_NAME }} ./${{ inputs.APP_NAME }} --install --namespace ${{ inputs.LOCATION }}

      - name: Clear artifacts
        shell: bash
        run: |
          rm -rf ~/.kube
