name: Helm Release TA system

on:
  workflow_call:
    inputs:
      LOCATION:
        type: string
        required: true
      BUILD:
        description: "Actual boolean flag to make build docker image, BUT BEWARE IT IS PASSING AS STRING"
        type: string
        required: false
      DOCKERFILE:
        description: "Dockerfile path relative to context"
        type: string
        required: false
        default: "./tools/Dockerfile"
      CONTEXT:
        description: "Context for dockerfile"
        type: string
        required: false
        default: "."
      APP_SYSTEM:
        description: "Common chart for system"
        type: string
        required: true
        default: ''
      DOCKER_REGISTRY:
        description: "Docker registry for helm chart"
        type: string
        required: false
        default: "docker-registry.trendagent.ru:5000"
      DRY_RUN:
        description: "Generate manifests"
        type: string
        required: false
    secrets:
      DEV_KUBE_CONFIG:
        required: false
      ROOT_TOKEN:
        required: true
      DOCKER_REGISTRY_USER:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true
      GPT_TOKEN:
        required: true

jobs:
  version:
    uses: trend-dev/workflows/.github/workflows/version.yml@master

  test:
    needs: version
    uses: trend-dev/workflows/.github/workflows/unit-test.yaml@master
    secrets: inherit