name: Run smoke test

on:
  workflow_call:

jobs:
  qa_test:
    runs-on: [ self-hosted, docker-runner ]
    steps:
      - name: run tests on QA clusters
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'http://94.26.226.163:8000/buildByToken/buildWithParameters?token=token_to_start_job&taEnv=STAGE&taCity=SPB&job=TA%20smoke'
          method: 'POST'
          username: ${{ secrets.QA_AUTH_USER }}
          password: ${{ secrets.QA_AUTH_PASSWORD }}
          ignoreStatusCodes: '404,401'
