name: Run unit tests

on:
  workflow_call:
    inputs:
      TEST:
        description: "Run unit tests"
        type: string
        required: false
        default: 'false'
    secrets:
      GPT_TOKEN:
        required: true

jobs:
  Run_unit_tests:
    if: inputs.TEST == 'true'
    name: Test & build & push docker image
    runs-on: [ self-hosted, docker-runner ]
    needs: variables
    steps:
      - name: Setup node
        id: node_build
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@trend-dev'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPT_TOKEN }}
          CI: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: run tests
        run: |
          npm ci
          npm run test