name: Get version

on:
    workflow_call:
        # Map the workflow outputs to job outputs
        outputs:
            app_name:
                description: "application name"
                value: ${{ jobs.parse.outputs.output1 }}
            app_version:
                description: "application version"
                value: ${{ jobs.parse.outputs.output2 }}

jobs:
    parse:
        name: Generate output
        runs-on: ubuntu-latest
        # Map the job outputs to step outputs
        outputs:
            output1: ${{ steps.step1.outputs.name }}
            output2: ${{ steps.step2.outputs.version }}
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v2
            -   id: step1
                run: echo "::set-output name=name::$(awk -F "\"" '/name/{print $4; exit}' ./package.json)"
            -   id: step2
                run: echo "::set-output name=version::$(awk -F "\"" '/version/{print $4; exit}' ./package.json)"
            -   shell: bash
                run: |
                    echo ${{ steps.step1.outputs.name }}
                    echo ${{ steps.step2.outputs.version }}
